#ifndef MVTYPES_H
#define MVTYPES_H

enum class ViewType {LIBTREEVIEW, LIBTABLEVIEW, LIBLISTVIEW, LIBSYMBOLEDITORVIEW, LIBFOOTPRINTEDITORVIEW};
enum class ModelType {SQLTABLEMODEL, SQLTREEMODEL, EXAMPLETREEMODEL};

#endif // MVTYPES_H
