#ifndef MVTYPES_H
#define MVTYPES_H

enum class ViewType {INVALID, LIBTREEVIEW, LIBTABLEVIEW, LIBLISTVIEW, LIBSYMBOLVIEW, LIBFOOTPRINTVIEW};
//enum class ModelType {INVALID, SQLTABLEMODEL, SQLTREEMODEL, EXAMPLETREEMODEL};

#endif // MVTYPES_H
